// Filenames inside ./images/. Regenerate by listing the folder.
window.ALL_WALL_IMAGES = [
  'hc_set_01_tile_03_x_cross_16px.png',
  'hc_set_01_tile_06_diagonal_16px.png',
  'hc_set_03_tile_01_diagonal_16px.png',
  'hc_set_10_tile_10_diamond_32px.png',
  'mixed_hc_tile_005_light_ordered_confetti_35.png',
  'mixed_hc_tile_007_dark_crosshatch_patch_24.png',
  'mixed_hc_tile_008_dark_stipple_clusters.png',
  'mixed_hc_tile_018_dark_ordered_confetti_25.png',
  'mixed_hc_tile_021_dark_stipple_clusters.png',
  'mixed_hc_tile_029_light_stipple_clusters.png',
  'mixed_hc_tile_081_light_ordered_confetti_35.png',
  'mixed_hc_tile_084_dark_stipple_clusters.png',
  'mixed_hc_tile_088_dark_typewriter_marks.png',
  'mixed_hc_tile_089_light_ordered_confetti_35.png',
  'mixed_hc_tile_091_dark_crosshatch_patch_24.png',
  'mixed_hc_tile_092_dark_stipple_clusters.png',
  'mixed_hc_tile_093_light_ribbon_cross_24.png',
  'textile_tile_06_256px_bw_seamless_basket_noise_12.png',
  'textile_tile_22_256px_bw_seamless_broken_hatch_16.png',
  'textile_tile_36_256px_bw_seamless_offset_slubs_8.png',
  'textile_tile_43_256px_bw_seamless_diagonal_twill_24.png',
];
