// Generated by scripts/build-manifest.mjs — do not edit by hand.
window.HYPERGAL_MANIFEST = {
  "pieces": [
    {
      "slug": "001-drift",
      "title": "drift",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "A field of slowly drifting points on a low-contrast ground. Generative, runs forever."
    },
    {
      "slug": "002-all-wall",
      "title": "all-wall",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "A patterned wall of falling bricks. One color pair and one high-contrast textile tile seed each run; staggered rows scroll downward while new faux-3D bricks tumble in from above, flatten, and join the wall. Click to reshuffle."
    },
    {
      "slug": "003-unbreakable",
      "title": "unbreakable",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "Breakout in reverse. A single paddle that cannot miss bounces one ball upward; every impact lays a brick instead of breaking one, so the wall grows downward and a steady scroll carries it off the top. The build-front is clamped to a band far above the floor — so the wall can never reach the paddle — while the ball steers toward the most starved column to keep the front level. No player, no losing, no finish. Click to reshuffle."
    },
    {
      "slug": "004-hunt-prey-paint",
      "title": "hunt prey paint",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "An abstract ecosystem that paints itself in watercolour, then wipes the painting clean — forever. Over a quiet, Dune-like pixel terrain of slow plants that visibly fill in one pixel at a time, vector prey of many colours graze, grow quickly into larger bodies, and flee hunters with their own alertness and sprint speed. Hunters are black arrows that run prey down, fatten, and breed only by splitting in half. Death paints; old age renews. Floored and capped so neither side ever wins. Click to reseed; ?warm= opens it already alive; ?debug for stats."
    },
    {
      "slug": "005-only-invaders",
      "title": "Only Invaders",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "Space Invaders after the invaders have vanished. Four defenders hold the top, right, bottom, and left edges, trading single shots, sudden volleys, and rare charged super bullets across an empty center. Every bullet is intercepted in midair; super bullets detonate in a white-screen shock that clears the field and resets the scores."
    },
    {
      "slug": "006-only-centipede",
      "title": "Only Centipede",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "A Centipede riff with small defenders at the top and bottom, one straight bullet each, and fast, hard-edged centipedes that enter from offscreen once the field is nearly cleared. Head shots remove the head and promote the next segment; body shots split the chain. Every hit segment becomes a three-shot mushroom that dents and deforms in the centipede's color."
    },
    {
      "slug": "007-hydra",
      "title": "hydra",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "Autonomous snake on an Apple //e amber CRT. A snake greedily hunts the nearest mouse, blind to its own body — so a long one curls into its own tail, and where it strikes itself it splits into two snakes that hunt on their own. The myth: cut the hydra and it doubles. The cull is the heads — when two snakes meet head-on, one dies. Eating lengthens, splitting divides, collisions thin the herd, and the count breathes forever with no player. Amber phosphor, scanlines, glow. Click to reseed."
    },
    {
      "slug": "008-vectrex-asteroids",
      "title": "Vectrex Asteroids",
      "year": 2026,
      "type": "interactive",
      "thumbnail": "thumbnail.svg",
      "description": "A black-and-white Vectrex-style Asteroids variant. The ship can keep only three shots alive at once. Asteroids never vanish: every hit fractures their matter into smaller vector shards, and the shards slowly pull back together until the rock reforms. The ship dies on contact."
    }
  ]
};
